# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "mutest-operators"
version = "0.0.0"
edition = "2024"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
mutest-emit = { path = "../mutest-emit" }
