[package]
name = "mutest-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
mutest-driver-cli = { path = '../mutest-driver-cli' }
mutest-json = { path = '../mutest-json' }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smallvec = { version = "1.15", features = ["serde"] }
clap = { version = "4", features = ["cargo", "derive"] }

[features]
default = []
rustc = []
