name: tests

on:
  push:
    branches:
      - "main"
    pull_request:
      - "main"
    workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Rust toolchain specified in rust-toolchain.toml.
      - name: Install Rust toolchain
        run: rustc --version

      - name: Build mutest-json (without rustc options, as a public consumer)
        run: cargo build -p mutest-json

      - name: Build mutest-runtime
        run: cargo build --release -p mutest-runtime

      - name: Build mutest-runtime-embedded-target-stub and test-metadata-shim for host
        run: |
          cargo build --release -p test-metadata-shim
          cargo build --release -p mutest-runtime-embedded-target-stub

      - name: Build mutest-driver with runtime embedding
        run: cargo build --release -p mutest-driver --features embed-runtime

      - name: Install mutest-driver and cargo-mutest
        run: |
          cargo install --force --path mutest-driver
          cargo install --force --path cargo-mutest

      - name: Run unit tests
        run: |
          cargo test -p cargo-mutest --no-fail-fast -- --color=always
          cargo test -p mutest-runtime --no-fail-fast -- --color=always

      - name: Run UI tests
        run: cargo ui-test
